//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPeliculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comentario()
        {
            this.Comentarios1 = new HashSet<Comentario>();
        }
    
        public int ComentarioID { get; set; }
        public Nullable<int> PeliculaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public string Comentario1 { get; set; }
        public Nullable<System.DateTime> FechaComentario { get; set; }
        public Nullable<int> RespuestaAComentarioID { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentarios1 { get; set; }
        public virtual Comentario Comentario2 { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
